language: python
os:
  - linux
python:
  - "2.7"
  - "3.6"
env:
  - PANDAS=0.17.1
  - PANDAS=0.21.0
  - PANDAS=0.20.3
  - PANDAS=latest
install:
  - pip install --only-binary=numpy,scipy numpy scipy
  - if [ $PANDAS=latest ]; then pip install pandas; else pip install pandas==$PANDAS; fi
  - pip install coverage coveralls
  - pip install -r requirements.txt
script:
  - coverage run --source great_expectations -m pytest tests
  - coveralls
